### ISSUE TITLE
Start Closed checkbox not changing anything

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/paragraphs_jquery_ui_accordion#13]
I had a strange problem this afternoon when I wanted to have an accordion start open.  Start closed is not checked.  My config file has "startclosed": 0, in it.

However after going to the page with the accordion, it is still closed.  When I view source of the page and search for closed I see "startclosed":true.

It shouldn't ever say true, it should either be a 0 or 1.

I am quite confused by this.  I should note that the Auto scroll checkbox does the same thing.

**Comment by yorkshire-pudding** [comment]
I think I might have found why this is; perhaps they've never worked but I've never noticed before.  I'll do some testing.

**Comment by yorkshire-pudding** [comment]
@keiserjb - I've added a PR that fixes the settings not being passed.

~~Autoscroll is still not working and I can't figure out why not; it seems to be to do with the event not firing as I put a load of `console.log()` lines in and they were only triggered when the page loads. 
Unless you know of a quick fix, I'm minded to merge this one so that startclosed works and open a separate issue for autoscroll.~~

**Comment by yorkshire-pudding** [comment]
Autoscroll now works

**Comment by alanmels** [comment]
@keiserjb Thanks for reporting this issue. @yorkshire-pudding Unfortunately, I don't have time to test this, if it's working for you, can you merge the changes and release a new version?

**Comment by yorkshire-pudding** [comment]
@alanmels - yes, of course. As a courtesy, I'm waiting for @keiserjb to confirm that it works before merging and releasing.
